[phases.setup]
nixPkgs = ['bun', 'nodejs_23']
nodeVersion = "23.3.0"

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = ['bun run railway:build']

[start]
cmd = 'cd apps/eliza && bun run start'